package me.videa.application;


/**
 * Session绠＄悊绫»
 * @author Vickie Tang
 * @version 1.0
 *
 */
public class SessionManager {
	
	private static Session session;
	private static SessionManager sessionManager;

	private SessionManager() {
		// TODO Autogenerated constructor stub
	}
	
	/**
	 * 鑾峰緱SessionManager瀵硅薄
	 * @return SessionManager
	 */
	public static SessionManager getSessionManager(){
		if(sessionManager == null){
			sessionManager = new SessionManager();
			session = new Session();
		}
		return sessionManager;
	}
	
	/**
	 * 鑾峰緱Session瀵硅薄
	 * @return session
	 */
	public Session getSession(){
		return session;
	}
	
	/**
	 * 淇®鏀规垨璁剧疆Session涓­鐨勫€¼
	 * @param key 閿®
	 * @param value  鍊¼
	 */
	public void setSession(String key, String value){
		session.put(key, value);
	}

}

