package me.videa.voice.show;

import java.util.Timer;
import java.util.TimerTask;

import me.videa.base.functions.BatteryReceiver;
import me.videa.base.functions.DateTimeReceiver;
import me.videa.effects.MainShowView;
import me.videa.voice.R;
import me.videa.voice.service.SpeechIntelligence;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.telephony.PhoneStateListener;
import android.telephony.SignalStrength;
import android.telephony.TelephonyManager;
import android.util.Log;
import android.widget.Toast;

import com.lidroid.xutils.ViewUtils;
import com.lidroid.xutils.view.annotation.ContentView;
import com.lidroid.xutils.view.annotation.ViewInject;

@ContentView(R.layout.activity_voice_main)
public class VoiceMainActivity extends Activity implements HandlerWhat {

	private final static String TAG = "VoiceMainActivity";

	@ViewInject(R.id.mainView)
	private static MainShowView mVoiceView;
	public static Handler mHandler;
	private Message mMessage;
	private Bundle mBundle;
	private Context mContext;
	/*
	 * This variables need to be global, so we can used them onResume and
	 * onPause method to
	 * 
	 * stop the listener
	 */

	TelephonyManager mTel;

	StateListener mStateListener;

	private BatteryReceiver mBatteryReceiver;
	
	private DateTimeReceiver mDateTimeReceiver;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Autogenerated method stub
		super.onCreate(savedInstanceState);
		ViewUtils.inject(this);
		mContext = this;
		mHandler = new ViewHandler();
		mStateListener = new StateListener();
		mTel = (TelephonyManager) getSystemService(Context.TELEPHONY_SERVICE);
		registerBatteryReceiver();
		registerDateTimeReceiver();
	}

	@Override
	protected void onResume() {
		mTel.listen(mStateListener, PhoneStateListener.LISTEN_SIGNAL_STRENGTHS);
		super.onResume();
	}

	@Override
	protected void onDestroy() {
		// TODO Autogenerated method stub
		unregisterReceiver();
		super.onDestroy();
	}

	@Override
	public void onBackPressed() {
		// TODO Autogenerated method stub
		super.onBackPressed();
	}

	class ViewHandler extends Handler {
		Bundle bundle;
		ExtraBean mBean;

		@Override
		public void dispatchMessage(Message msg) {
			// TODO Autogenerated method stub
			bundle = msg.getData();
			switch (msg.what) {
			case NET_STATE:
				int singleStrenth = bundle.getInt("state");
				Log.d(TAG, "" + singleStrenth);
				mBean = new ExtraBean();
				mBean.setIp(bundle.getString("ip"));
				mBean.setSingleStrength(singleStrenth);
				mVoiceView.reDraw(NET_STATE, mBean);
				break;
			case BATTERY_STATE:
				Log.d(TAG, "level : " + bundle.getInt("level") + " scale : "
						+ bundle.getInt("scale"));
				mBean = new ExtraBean();
				Toast.makeText(mContext, bundle.getInt("level") + "",
						Toast.LENGTH_LONG).show();
				mBean.setBatteryLevel(bundle.getInt("level"));
				mVoiceView.reDraw(BATTERY_STATE, mBean);
				break;
			case DATE_STATE:
				mBean = new ExtraBean();
				mBean.setTimeBean((TimeBean)bundle.getSerializable("time"));
				mVoiceView.reDraw(DATE_STATE, mBean);
				break;

			default:
				break;
			}
			super.dispatchMessage(msg);
		}

	}

	/**
	 * 启动时间及气温刷新线程
	 */
	private void startTimer() {
		Timer mTimer = new Timer();
		mTimer.schedule(new TimerTask() {

			@Override
			public void run() {
				// TODO Autogenerated method stub
				mHandler.sendEmptyMessage(NET_STATE);
			}
		}, 0, 6 * 1000);
	}

	/* Start the PhoneState listener */

	private class StateListener extends PhoneStateListener

	{

		/*
		 * Get the Signal strength from the provider
		 */

		@Override
		public void onSignalStrengthsChanged(SignalStrength signalStrength)

		{

			super.onSignalStrengthsChanged(signalStrength);
			mMessage = new Message();
			mMessage.what = NET_STATE;
			mBundle = new Bundle();
			mBundle.putInt("state", signalStrength.getGsmSignalStrength());
			mBundle.putString("ip",
					NetState.getLocalIpAddress(VoiceMainActivity.this));
			mMessage.setData(mBundle);
			mHandler.sendMessage(mMessage);
		}

	};

	/**
	 * 注册电量广播接收器
	 */
	private void registerBatteryReceiver() {
		// 注册广播接受者java代码
		IntentFilter intentFilter = new IntentFilter(
				Intent.ACTION_BATTERY_CHANGED);
		// 创建广播接受者对象
		mBatteryReceiver = new BatteryReceiver(mHandler);

		// 注册receiver
		registerReceiver(mBatteryReceiver, intentFilter);
	}

	/**
	 * 注册时间广播接收
	 */
	private void registerDateTimeReceiver() {
		// 注册广播接受者java代码
		IntentFilter mFilter = new IntentFilter(
				Intent.ACTION_TIME_TICK);
		// 创建广播接受者对象
		mDateTimeReceiver = new DateTimeReceiver(mHandler);

		// 注册receiver
		registerReceiver(mDateTimeReceiver, mFilter);
	}
	
	/**
	 * 反注册所有广播
	 */
	private void unregisterReceiver(){
		unregisterReceiver(mBatteryReceiver);
		unregisterReceiver(mDateTimeReceiver);
	}

	/**
	 * 启动语音服务
	 */
	void startVoiceService() {
		Intent mService = new Intent(this, SpeechIntelligence.class);
		startService(mService);
	}

}
