package me.videa.functions.remote;

import me.videa.base.functions.Contacts;
import android.content.Context;
import android.os.AsyncTask;
import android.widget.Toast;

public class LocalDataAsyncTask extends AsyncTask<String, String, String>{
	
	private Context mContext;
	
	public <T> LocalDataAsyncTask(Context context, T param){
		this.mContext = context;
	}

	@Override
	protected String doInBackground(String... params) {
		// TODO Autogenerated method stub
		//娴嬭瘯璇诲彇鑱旂郴浜轰俊鎭¯
//		String result = new Contacts(mContext).getContacts();
		try {
//			result = new Contacts(mContext).searchContactNameByNumber("02536598622");
//			result = new Contacts(mContext).searchContactNumberByName("娴嬭瘯");
			new Contacts(mContext).addContact("鍞愪細鏃", "18905166144", "123@126.com");
		} catch (Exception e) {
			// TODO Autogenerated catch block
			e.printStackTrace();
		}
		return null;
	}

	@Override
	protected void onCancelled() {
		// TODO Autogenerated method stub
		super.onCancelled();
	}

	@Override
	protected void onCancelled(String result) {
		// TODO Autogenerated method stub
		super.onCancelled(result);
	}

	@Override
	protected void onPostExecute(String result) {
		// TODO Autogenerated method stub
		if(result == null){
			Toast.makeText(mContext, "鑾峰彇鑱旂郴浜哄け璐¥", Toast.LENGTH_LONG).show();
		}		
		super.onPostExecute(result);
	}

	@Override
	protected void onPreExecute() {
		// TODO Autogenerated method stub
		super.onPreExecute();
	}

	@Override
	protected void onProgressUpdate(String... values) {
		// TODO Autogenerated method stub
		super.onProgressUpdate(values);
	}
	
	

}

