package me.videa.functions.remote;

import java.util.List;
import java.util.Map;

import me.videa.voice.R;
import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.util.Log;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

/**
 * 灞曠ず杩滅▼鏂囦欢鐩®褰
 * @author pactera
 *
 */
public class RemoteFileShow extends Activity{
	
	private final static String TAG = "RemoteFileShow";
	
	TextView mCurrent_path;
	ListView mListView;
	List<Map<String, String>> mListData;
	RemoteFileShowAdapter adapter;
	Context mContext;
	
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Autogenerated method stub
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_remote_file_show);
		mContext = this;
		initViews();
		loadData();
	}
	
	private void loadData(){
		new RemoteFileLoaderTask(RemoteFileShow.this, mCurrent_path.getText().toString(), new RemoteFileLoaderCallback() {
			
			@Override
			public void setResult(List<Map<String, String>> result, String currentPath) {
				// TODO Autogenerated method stub
				Log.d(TAG, currentPath);
				adapterData(result, currentPath);
			}
		}).execute("");
	}
	
	
	private void adapterData(List<Map<String, String>> result, String currentPath){
		if(result == null){
			Toast.makeText(RemoteFileShow.this, R.string.load_err, Toast.LENGTH_LONG).show();
			return;
		}
		//濡傛灉褰撳墠璺¯寰勪负null锛屽垯閫€鍑篴ctivity
		if(currentPath == null){
			finish();
		}
		this.mListData = result;
		this.mCurrent_path.setText(currentPath);
		adapter = new RemoteFileShowAdapter(mContext, mListData);
		mListView.setAdapter(adapter);
		adapter.notifyDataSetChanged();
		
	}
	
	private void initViews(){
		mCurrent_path = (TextView) findViewById(R.id.current_path_name);
		mListView = (ListView) findViewById(R.id.current_content);
	}

	@Override
	public void finish() {
		// TODO Autogenerated method stub
		Log.d(TAG, "閫€鍑虹洰褰 ");
		super.finish();
	}

	@Override
	public void onBackPressed() {
		// TODO Autogenerated method stub
		String mPath = mCurrent_path.getText().toString();
		if(mPath == "/"){
			mPath = null;
		}
		if(mPath != null){
			//鑻ュ綋鍓嶇洰褰曚笉鏄¯鏍圭洰褰曪紝鍒欓€€鍥炰笂绾х洰褰
			//鑻ヤ负鏍圭洰褰曪紝鍒欓€€鍑篈ctivity
			if(mPath.indexOf("/") > 0){
				mPath = mPath.substring(0, mPath.lastIndexOf("/"));
				adapterData(HistoryDataCache.initCache().getCache(mPath), mPath);
				return;
			}			
		}
		super.onBackPressed();
	}	

	@Override
	protected void onDestroy() {
		// TODO Autogenerated method stub
		super.onDestroy();
	}

	@Override
	protected void onResume() {
		// TODO Autogenerated method stub
		super.onResume();
	}
	
	

}

