package me.videa.functions.analysis;



public abstract class AbstractAnalyse implements Analysis{	
	
	private Encrypt mEncrypt;
	
	public AbstractAnalyse() {
		// TODO Autogenerated constructor stub
	}
	
	public AbstractAnalyse(Encrypt encrypt) {
		// TODO Autogenerated constructor stub
		this.mEncrypt = encrypt;
	}
	
	/**
	 * 鑾峰彇瀵嗛挜
	 * @param encryptType鍔犲瘑鏂瑰紡
	 * @return 瀵嗛挜
	 */
	String getEncryptKey(String encryptType) {
		// TODO Autogenerated method stub
		if(encryptType.equals("md5")){
			return mEncrypt.getMd5Key();
		}
		return mEncrypt.getDefaultKey();
	}	
	
}

