package me.videa.functions.analysis;


public class Md5Encrypt extends DefaultEncrypt{
	
	public Md5Encrypt() {
		// TODO Autogenerated constructor stub
		super();
	}

	@Override
	public
	String getMd5Key() {
		// TODO Autogenerated method stub
		return null;
	}
	

}

