package me.videa.effects;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.util.AttributeSet;
import android.view.View;

public class AppView extends View{
	
	protected Paint mPaint;
	
	/**
	 * 鏈€浜®鐨勫渾鍦堥¢滆壊
	 */
	public static String mColorBrighter = "#00b7b5";
	/**
	 * 绋嶆殫鐨勫渾鍦堥¢滆壊
	 */
	public static String mColor = "#01a7a5";
	/**
	 * 鏈€鏆楃殑鍦嗗湀棰滆壊
	 */
	public static String mColorDarker = "#003b39";

	public AppView(Context context, AttributeSet attrs, int defStyleAttr) {
		super(context, attrs, defStyleAttr);
		// TODO Autogenerated constructor stub
	}

	public AppView(Context context, AttributeSet attrs) {
		super(context, attrs);
		// TODO Autogenerated constructor stub
	}

	public AppView(Context context) {
		super(context);
		// TODO Autogenerated constructor stub
	}
	
	/**
	 * 缁樺埗鐩寸嚎
	 * @param canvas   鐢诲竷
 	 * @param pts      鐐规暟缁
	 */
	protected void drawLine(Canvas canvas, float startX, float startY, float stopX, float stopY) {
		canvas.drawLine(startX, startY, stopX, stopY, mPaint);
	}
	
	/**
	 * 缁樺埗鏂囧瓧 
	 * @param canvas  鐢诲竷
	 * @param text    鏂囧瓧
	 * @param x       x 
	 * @param y       y
	 */
	protected void drawText(Canvas canvas, String text, float x, float y) {
		canvas.drawText(text, x, y, mPaint);
	}
	

}

