package me.videa.effects;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.RectF;
import android.util.AttributeSet;

public class RectangleView extends AppView{
	
	public RectangleView(Context context, AttributeSet attrs, int defStyleAttr) {
		super(context, attrs, defStyleAttr);
		// TODO Autogenerated constructor stub
	}

	public RectangleView(Context context, AttributeSet attrs) {
		super(context, attrs);
		// TODO Autogenerated constructor stub
	}

	public RectangleView(Context context) {
		super(context);
		// TODO Autogenerated constructor stub
	}
	
	/**
	 * 缁樺埗鐭╁舰
	 * @param canvas  鐢诲竷
	 * @param x       x
	 * @param y       y
	 * @param width   鐭╁舰瀹藉害
	 * @param height  鐭╁舰楂樺害
	 */
	protected void drawRect(Canvas canvas, float x, float y, float width, float height) {
		RectF rect = new RectF(x, y, x + width, y + height);
		canvas.drawRect(rect, mPaint);
	}

}

